on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ self-hosted ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u robert mkdir -p /home/robert/ansible/
          sudo chown -R robert:robert /home/robert/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u robert bash -c 'cat > /home/robert/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              webservers:
                hosts:
                  web01:
                    ansible_host: 10.184.0.2 #node1
                    ansible_user: robert
                    

              databases:
                hosts:
                  db01:
                    ansible_host: 10.174.0.2 #node2
                    ansible_user: robert
                    db_version: 14
                   

              
          EOF
